mybatis:
  mapper-locations: classpath*:mappers/cache/**/*.xml
spring:
  datasource:
    url: jdbc:mysql://dm1509337294777.fun25.co.kr:19002/cache?autoReconnect=true
    driverClassName:  com.mysql.cj.jdbc.Driver
    username: basic
    password: 1234
---    
spring:
  cache:
    ehcache:
      config: classpath:ehcache.xml